
name: Update NueXini Packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4,16,23 * * *'

env:
  shell: main.sh
  README: other/AAAAA/README.md

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install git subversion git-core wget
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        chmod +x $shell
        git clone https://github.com/NueXini/NueXini_Packages -b main --single-branch packages
        cd packages
        rm -rf *
        $GITHUB_WORKSPACE/$shell

    - name: Upload packages
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        [ -e $README ] && cp -f $README packages
        cd packages
        git add .
        git commit -m "❤️update at $(TZ='Asia/Shanghai' date +%Y-%m-%d)🍭"
        git push --quiet "https://${{ secrets.TOKEN }}@github.com/NueXini/NueXini_Packages.git" HEAD:main
 
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v1.2.3
      with:
        retain_days: 1
        keep_minimum_runs: 0

