name: Test

on:
  workflow_dispatch:

env:
  shell: main.sh
  README: other/AAAAA/README.md


jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "Asia/Shanghai"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone packages
      run: |
        chmod +x $shell
        git clone https://github.com/NueXini/NueXini_Packages -b main --single-branch packages
        cd packages
        $GITHUB_WORKSPACE/$shell
